version: '3.7'

services:
  contact_server:
    build:
      context: ./contact_server
    volumes:
      - ./contact_server:/app
    env_file:
      - dev.env
    command: node_modules/nodemon/bin/nodemon.js -w /app /app/src/index.js
    ports:
      - 3000:3000

  contact_lint:
    build:
      context: ./contact_server
    volumes:
      - ./contact_server:/app
    command: ./node_modules/.bin/eslint .

  contact_tests:
    build:
      context: ./contact_server
    volumes:
      - ./contact_server:/app
    command: ./node_modules/.bin/lab tests

  database:
    image: mongo:4.1.11
    volumes:
      - "./database_data:/data/db"
    env_file:
      - dev.env
    expose:
      - 27017

  contact_front:
    build:
      context: ./contact_front
    volumes:
      - ./contact_front:/app
    command: ./node_modules/.bin/webpack-dev-server --mode development --config config/webpack.config.js --host 0.0.0.0
    ports:
      - 8080:8080
